Sprint 04
AlwaysWannaPower/MovieQuiz-ios-AWP pull request #1
Opened 2022-12-21 05:38 UTC by AlwaysWannaPower

Дооообрый день) 
Принес на ваш суд - свою версию
Как и у многих, проблема со шрифтами. Применял шрифт окольными путями, ибо "нуу не отображаются он в списке" 
Собаку съел на статьях, в том числе и документации от Элл. Даже наставник видео записал, все сделал по шагах - ничего. 
Хкод версия 14.0.1  - сейчас попробую обновить и сделаю по канону шрифт, если будут изменения. 

Хорошего настроения и приятного дня)

2022-12-21 21:02 UTC, ABashkirova requested changes
Со шрифтами не все так плохо, по крайней мере у меня верхние лейблы даже прогрузились в верных шрифтах. Текст вопроса вот что-то гуляет, ты начал пытаться через атрибуты выставлять. 

что точно нужно проверить:
- установлены ли шрифты у тебя на компьютер
- дополнительно проверить info.plist, мне кажется без расширения шрифты лучше указать (перепроверь по учебнику)

Плюс я заметила, как лагает Xcode если начинаешь перевыбирать семейство шрифтов.
Попробуй выставить системный шрифт, в regular. Затем смени на кастом и попробуй выбрать группу шрифтов YS – долджен быть не по алфавиту, а в самом верху списка. И так туда обратно, вдруг прочухается. 
Выглядит так, что сториборды сильно глючат, если правильного начертания шрифта не подключено (мы подключаем только два Bold/Medium )

2022-12-21 21:03 UTC, ABashkirova commented
Обрати внимание на цвета в макете, и в твоем проекте
<img width="377" alt="Снимок экрана 2022-12-21 в 22 46 10" src="https://user-images.githubusercontent.com/20269264/209002180-af92984f-f759-432c-9244-eeadc64c4d52.png"> <img width="377" alt="Снимок экрана 2022-12-21 в 22 46 52" src="https://user-images.githubusercontent.com/20269264/209002170-bc9808d2-0452-4ddb-a393-d2f953bb1842.png">

2022-12-22 16:14 UTC, AlwaysWannaPower commented
Исправил все критические ошибки, в том числе касательно шрифтов. Теперь все чики - пики :D 
Замечания касательно код стайла - тоже исправил. Бессознательно вносил правки под свифтЛинтом, впредь буду с головой это делать. 

Спасибо за полный фидбек и хорошего настроения :)

2022-12-22 20:41 UTC, ABashkirova commented
Рада, что получилось поправить все :)

только вот шрифты теперь лежат где-то на твоем компьютере, а в проекте ссылка относительная :) давай править срочно, я же запустить не смогу
<img width="1512" alt="Снимок экрана 2022-12-22 в 22 39 51" src="https://user-images.githubusercontent.com/20269264/209222223-b4d79c7a-da8b-4210-aa9e-bab639fdecd6.png">

2022-12-23 04:09 UTC, closed without merging